modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="coldweaponcraftsmanship"
version="0.1.0"
displayName="Cold Weapon Craftsmanship"
description="Cold Weapon Craftsmanship is a mod that guides players in crafting realistic cold weapons."

[[dependencies.coldweaponcraftsmanship]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.241,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.coldweaponcraftsmanship]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
